version: '3.8'

services:
  app:
    build:
      args:
        user: yar
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: translations
    container_name: translations-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - translations

  db:
    image: mariadb:10.4
    container_name: translations-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
        - translations
  nginx:
    image: nginx:alpine
    container_name: translations-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - translations

networks:
  translations:
    driver: bridge

volumes:
  database-data:
